import sqlite3 from 'sqlite3';

export type FilterOperator =
    | 'contains' | 'not-contains' | 'equals' | 'not-equals' | 'starts-with' | 'ends-with'
    | 'greater-than' | 'less-than' | 'greater-or-equal' | 'less-or-equal'
    | 'is-empty' | 'is-not-empty';

export interface Filter {
    id: string;
    entityId: string;
    fieldId: string;
    operator: FilterOperator;
    value: string | string[];
}

export interface View {
    id: string;
    name: string;
    entityId: string;
    filters: Filter[];
}

/**
 * Service for managing saved entity views (filter configurations) in SQLite.
 */
export class ViewService {
    private db: sqlite3.Database;

    constructor(db: sqlite3.Database) {
        this.db = db;
    }

    /**
     * Fetches all saved views from the database.
     * @returns A promise resolving to an array of View objects.
     */
    async getAll(): Promise<View[]> {
        const rows = await this.allQuery<{ id: string; name: string; entity_id: string; filters: string }>(
            'SELECT id, name, entity_id, filters FROM entity_views'
        );
        return rows.map(row => ({
            id: row.id,
            name: row.name,
            entityId: row.entity_id,
            filters: JSON.parse(row.filters),
        }));
    }

    /**
     * Fetches a single view by ID.
     * @param id - The view ID.
     * @returns A promise resolving to the View, or undefined if not found.
     */
    async getById(id: string): Promise<View | undefined> {
        const row = await this.getQuery<{ id: string; name: string; entity_id: string; filters: string }>(
            'SELECT id, name, entity_id, filters FROM entity_views WHERE id = ?',
            [id]
        );
        if (!row) {
            return undefined;
        }
        return {
            id: row.id,
            name: row.name,
            entityId: row.entity_id,
            filters: JSON.parse(row.filters),
        };
    }

    /**
     * Creates a new view, accepting the id from the caller.
     * @param id - The view ID (generated by the frontend).
     * @param name - The display name for the view.
     * @param entityId - The entity this view belongs to.
     * @param filters - The filter conditions to persist.
     * @returns A promise resolving to the created View.
     */
    async create(id: string, name: string, entityId: string, filters: Filter[]): Promise<View> {
        const filtersJson = JSON.stringify(filters);
        await this.runQuery(
            'INSERT INTO entity_views (id, name, entity_id, filters) VALUES (?, ?, ?, ?)',
            [id, name, entityId, filtersJson]
        );
        return { id, name, entityId, filters };
    }

    /**
     * Deletes a view by ID.
     * @param id - The view ID to delete.
     */
    async delete(id: string): Promise<void> {
        await this.runQuery('DELETE FROM entity_views WHERE id = ?', [id]);
    }

    private runQuery(sql: string, params: any[] = []): Promise<void> {
        return new Promise((resolve, reject) => {
            this.db.run(sql, params, (err) => {
                if (err) reject(err);
                else resolve();
            });
        });
    }

    private allQuery<T>(sql: string, params: any[] = []): Promise<T[]> {
        return new Promise((resolve, reject) => {
            this.db.all(sql, params, (err, rows) => {
                if (err) reject(err);
                else resolve(rows as T[]);
            });
        });
    }

    private getQuery<T>(sql: string, params: any[] = []): Promise<T | undefined> {
        return new Promise((resolve, reject) => {
            this.db.get(sql, params, (err, row) => {
                if (err) reject(err);
                else resolve(row as T | undefined);
            });
        });
    }
}
